// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSocialPerros.App.Persistencia;

namespace RedSocialPerros.App.Persistencia.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210912232500_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RedSocialPerros.App.Dominio.Amistad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("fecha_amistad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("perroAid")
                        .HasColumnType("int");

                    b.Property<int?>("perroBid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("perroAid");

                    b.HasIndex("perroBid");

                    b.ToTable("Amistades");
                });

            modelBuilder.Entity("RedSocialPerros.App.Dominio.Perro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raza")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Perros");
                });

            modelBuilder.Entity("RedSocialPerros.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("edad")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("perroid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("perroid");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RedSocialPerros.App.Dominio.Amistad", b =>
                {
                    b.HasOne("RedSocialPerros.App.Dominio.Perro", "perroA")
                        .WithMany()
                        .HasForeignKey("perroAid");

                    b.HasOne("RedSocialPerros.App.Dominio.Perro", "perroB")
                        .WithMany()
                        .HasForeignKey("perroBid");

                    b.Navigation("perroA");

                    b.Navigation("perroB");
                });

            modelBuilder.Entity("RedSocialPerros.App.Dominio.Persona", b =>
                {
                    b.HasOne("RedSocialPerros.App.Dominio.Perro", "perro")
                        .WithMany()
                        .HasForeignKey("perroid");

                    b.Navigation("perro");
                });
#pragma warning restore 612, 618
        }
    }
}
